<?php
/**
 * OIDC Keys Loader
 *
 * Loads the OIDC signing keys for the OpenID Connect Server plugin.
 * Generated by Soli Passport Plugin.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$oidc_keys_dir = WP_CONTENT_DIR . '/oidc-keys';

if ( file_exists( $oidc_keys_dir . '/public.key' ) && file_exists( $oidc_keys_dir . '/private.key' ) ) {
	define( 'OIDC_PUBLIC_KEY', file_get_contents( $oidc_keys_dir . '/public.key' ) );
	define( 'OIDC_PRIVATE_KEY', file_get_contents( $oidc_keys_dir . '/private.key' ) );
}

/**
 * Show warning when Soli Passport Plugin is deactivated but keys still exist.
 */
add_action( 'admin_notices', function () {
	// Only run if passport plugin is NOT active
	if ( defined( 'SOLI_PASSPORT__PLUGIN_VERSION' ) ) {
		return;
	}

	// Only show on plugins page
	$screen = get_current_screen();
	if ( ! $screen || $screen->id !== 'plugins' ) {
		return;
	}

	?>
	<div class="notice notice-warning">
		<p><strong>Soli Passport Plugin is deactivated but OIDC keys still exist.</strong></p>
		<p>If you delete the Soli Passport Plugin, the following will be permanently removed:</p>
		<ul style="list-style: disc; margin-left: 20px;">
			<li>All OIDC signing keys (wp-content/oidc-keys/)</li>
			<li>This mu-plugin (oidc-keys-loader.php)</li>
			<li>All registered OIDC clients and role mappings</li>
		</ul>
		<p><strong>This will break all applications using this site as their identity provider.</strong></p>
	</div>
	<?php
} );